/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MonumentData = IDL.Record({
  'latitude' : IDL.Float64,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'history' : IDL.Text,
  'imageUrl' : IDL.Text,
  'longitude' : IDL.Float64,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMonuments' : IDL.Func([], [IDL.Vec(MonumentData)], ['query']),
  'getMonumentById' : IDL.Func([IDL.Nat], [MonumentData], ['query']),
  'getMonumentsNear' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(MonumentData)],
      ['query'],
    ),
  'searchMonuments' : IDL.Func([IDL.Text], [IDL.Vec(MonumentData)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MonumentData = IDL.Record({
    'latitude' : IDL.Float64,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'history' : IDL.Text,
    'imageUrl' : IDL.Text,
    'longitude' : IDL.Float64,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMonuments' : IDL.Func([], [IDL.Vec(MonumentData)], ['query']),
    'getMonumentById' : IDL.Func([IDL.Nat], [MonumentData], ['query']),
    'getMonumentsNear' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(MonumentData)],
        ['query'],
      ),
    'searchMonuments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MonumentData)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };