/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MonumentData {
  'latitude' : number,
  'country' : string,
  'city' : string,
  'name' : string,
  'description' : string,
  'history' : string,
  'imageUrl' : string,
  'longitude' : number,
  'category' : string,
}
export interface _SERVICE {
  'getAllMonuments' : ActorMethod<[], Array<MonumentData>>,
  'getMonumentById' : ActorMethod<[bigint], MonumentData>,
  'getMonumentsNear' : ActorMethod<
    [number, number, number],
    Array<MonumentData>
  >,
  'searchMonuments' : ActorMethod<[string], Array<MonumentData>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];